// <auto-generated />
using System;
using DB_CK;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace OnTapCK2021_2022.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20240114163739_database")]
    partial class database
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("DB_CK.CANHO", b =>
                {
                    b.Property<string>("MaCanHo")
                        .HasMaxLength(5)
                        .HasColumnType("varchar");

                    b.Property<string>("TenChuHo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar");

                    b.HasKey("MaCanHo");

                    b.ToTable("cANHOs");
                });

            modelBuilder.Entity("DB_CK.NHANVIEN", b =>
                {
                    b.Property<string>("MaNhanVien")
                        .HasMaxLength(5)
                        .HasColumnType("varchar");

                    b.Property<string>("GioiTinh")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("varchar");

                    b.Property<string>("SoDienThoai")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar");

                    b.Property<string>("TenNhanVien")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar");

                    b.HasKey("MaNhanVien");

                    b.ToTable("NHANVIENs");
                });

            modelBuilder.Entity("DB_CK.NV_BT", b =>
                {
                    b.Property<string>("MaNhanVien")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("MaThietBi")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("MaCanHo")
                        .HasColumnType("varchar(255)");

                    b.Property<int>("LanThu")
                        .HasColumnType("int");

                    b.Property<DateTime?>("NgayBaoTri")
                        .HasColumnType("datetime(6)");

                    b.HasKey("MaNhanVien", "MaThietBi", "MaCanHo");

                    b.ToTable("NV_BTs");
                });

            modelBuilder.Entity("DB_CK.THIETBI", b =>
                {
                    b.Property<string>("MaThietBi")
                        .HasMaxLength(5)
                        .HasColumnType("varchar");

                    b.Property<string>("TenThietBi")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar");

                    b.HasKey("MaThietBi");

                    b.ToTable("THIETBIs");
                });
#pragma warning restore 612, 618
        }
    }
}
