// <auto-generated />
using System;
using DB_CK;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace OnTapCK.Migrations
{
    [DbContext(typeof(OnTapCKContext))]
    [Migration("20240112102419_DB_CK")]
    partial class DB_CK
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("DB_CK.CHUYENBAY", b =>
                {
                    b.Property<string>("MACH")
                        .HasMaxLength(5)
                        .HasColumnType("varchar");

                    b.Property<string>("CHUYEN")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar");

                    b.Property<string>("DDEN")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar");

                    b.Property<string>("DDI")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar");

                    b.Property<string>("GBAY")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar");

                    b.Property<string>("GDEN")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar");

                    b.Property<string>("MAMB")
                        .IsRequired()
                        .HasColumnType("varchar(5)");

                    b.Property<DateTime?>("NGAY")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("THUONG")
                        .HasColumnType("int");

                    b.Property<int>("VIP")
                        .HasColumnType("int");

                    b.HasKey("MACH");

                    b.HasIndex("MAMB");

                    b.ToTable("CHUYENBAY");
                });

            modelBuilder.Entity("DB_CK.CT_CB", b =>
                {
                    b.Property<string>("MACH")
                        .HasColumnType("varchar(5)");

                    b.Property<string>("MAHK")
                        .HasColumnType("varchar(5)");

                    b.Property<bool>("LOAIGHE")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("SOGHE")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("varchar");

                    b.HasKey("MACH", "MAHK");

                    b.HasIndex("MAHK");

                    b.ToTable("CT_CB");
                });

            modelBuilder.Entity("DB_CK.HANHKHACH", b =>
                {
                    b.Property<string>("MAKH")
                        .HasMaxLength(5)
                        .HasColumnType("varchar");

                    b.Property<string>("DIACHI")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar");

                    b.Property<string>("DIENTHOAI")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("varchar");

                    b.Property<string>("HOTEN")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar");

                    b.HasKey("MAKH");

                    b.ToTable("HANHKHACH");
                });

            modelBuilder.Entity("DB_CK.MAYBAY", b =>
                {
                    b.Property<string>("MAMB")
                        .HasMaxLength(5)
                        .HasColumnType("varchar");

                    b.Property<string>("HANGMB")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar");

                    b.Property<int>("SOCHO")
                        .HasColumnType("int");

                    b.HasKey("MAMB");

                    b.ToTable("MAYBAY");
                });

            modelBuilder.Entity("DB_CK.CHUYENBAY", b =>
                {
                    b.HasOne("DB_CK.MAYBAY", "MAYBAY")
                        .WithMany()
                        .HasForeignKey("MAMB")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MAYBAY");
                });

            modelBuilder.Entity("DB_CK.CT_CB", b =>
                {
                    b.HasOne("DB_CK.CHUYENBAY", "CHUYENBAY")
                        .WithMany()
                        .HasForeignKey("MACH")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DB_CK.HANHKHACH", "HANHKHACH")
                        .WithMany()
                        .HasForeignKey("MAHK")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CHUYENBAY");

                    b.Navigation("HANHKHACH");
                });
#pragma warning restore 612, 618
        }
    }
}
